// <auto-generated />
using System;
using APIGateway.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace APIGateway.Infrastructure.Migrations.AuthDb
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20241113183722_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("APIGateway.Domain.Entities.TokenPairAuthRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsOutdated")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(88)
                        .HasColumnType("character varying(88)");

                    b.HasKey("Id");

                    b.ToTable("TokenPairAuthRecords");
                });

            modelBuilder.Entity("APIGateway.Domain.Entities.TokenPairAuthRecord", b =>
                {
                    b.OwnsOne("Common.Domain.ValueObjects.MemberKey", "MemberId", b1 =>
                        {
                            b1.Property<Guid>("TokenPairAuthRecordId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("GuildId")
                                .HasColumnType("numeric(20,0)");

                            b1.Property<decimal>("UserId")
                                .HasColumnType("numeric(20,0)");

                            b1.HasKey("TokenPairAuthRecordId");

                            b1.ToTable("TokenPairAuthRecords");

                            b1.WithOwner()
                                .HasForeignKey("TokenPairAuthRecordId");
                        });

                    b.OwnsOne("Common.Domain.ValueObjects.RoleKey", "RoleId", b1 =>
                        {
                            b1.Property<Guid>("TokenPairAuthRecordId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("GuildId")
                                .HasColumnType("numeric(20,0)");

                            b1.Property<decimal>("RoleId")
                                .HasColumnType("numeric(20,0)");

                            b1.HasKey("TokenPairAuthRecordId");

                            b1.ToTable("TokenPairAuthRecords");

                            b1.WithOwner()
                                .HasForeignKey("TokenPairAuthRecordId");
                        });

                    b.Navigation("MemberId")
                        .IsRequired();

                    b.Navigation("RoleId")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
